home/urls.py
from django.urls import path
from home import views
urlpatterns = [
    path('home/', views.dashboard, name="home"),

    path('assignments/create/', views.create_assignment, name='add_assignment'),
    path('assignments/<id>/pass', views.pre_submission,
        name='pre_submission'),

    path('assignments/<id>/', views.assignment_detail),

    path('submissions/', views.all_submmission, name="all_submmission"),


    path('assignments/<id>/detail/', views.assignments_detail, name="assignments_detail"),

    path('assignments/', views.all_assignment, name='all_assignment'),

    path('submissions/all/', views.all_assignment_submmission, name='all_assignment_submmission'),

	path('assignments/<id>/delete', views.delete_assignment,
        name='delete_assignment'),

    path('assignments/<id>/edit', views.edit_assignment,
        name='edit_assignment'),

    path('assignments/<id>/submission/', views.submit_assignment,
        name='assignment_submission'),

    path('submissions/<id>/delete', views.delete_submission,
        name='delete_submission'),

    path('submissions/<id>/edit', views.edit_submission,
        name='submission_detail'),


    path('assignments/<id>/submissions', views.assignment_submissions,
        name='submissions'),

    path('assouncement/add/', views.create_Notification),
    path('notifications/', views.all_notification),
    path('test/', views.test)
    # path('notifications/clear/', views.clear_notifications),
]

school_management/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns+= static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

home/models.py
from django.db import models
import uuid
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from users.models import Profile
import os






class Assignment(models.Model):
    title = models.CharField(max_length=255)
    upload = models.FileField(upload_to='assignments/', null=True, default="No file uploaded")

    due_date = models.DateField()
    created_at = models.DateField(auto_now_add=True)
    last_updated = models.DateField(auto_now=True)
    # subject = models.ForeignKey(Profile.subject, on_delete=models.CASCADE,)

    descprition = models.CharField(null=True, blank=True, max_length=1000)
    submmetted_by = models.ManyToManyField(User, blank=True)
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='assignments'
    )

    def extension_ass(self):
        extension = os.path.splitext(self.upload.name)[1]
        return extension

    def __str__(self):
        return self.user.username + " created " + self.title



class Submission(models.Model):
    upload = models.FileField(upload_to='submissions/', default="No file uploaded")
    submitted_at = models.DateField(auto_now=True)
    descprition = models.CharField(null=True, blank=True, max_length=1000)
    last_updated = models.DateField(auto_now=True)
    assignment = models.ForeignKey(
        'Assignment',
        on_delete=models.CASCADE,
        related_name='submissions'
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='submissions'
    )

    def extension_sub(self):
        extension = os.path.splitext(self.upload.name)[1]
        return extension

    grade = models.CharField(max_length=100, null=True, blank=True, default="No grade yet")
    feedback = models.CharField(max_length=255, null=True, blank=True, default="No feedback yet")
    def __str__(self):
        return self.user.username + " submmitted " + self.assignment.title

home/views.py
######### Imports ##########33

from django.shortcuts import render,  redirect,  get_object_or_404
from django.contrib.auth.decorators import login_required
import os
import datetime
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from django.http import HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from users import forms
from home.models import Assignment, Submission
from users.models import Profile, Notification, Notification_general
import datetime
import os
from django.core.exceptions import ValidationError

###################################################################################################################################################

@login_required
def dashboard(request):
    assignment_form = forms.AssignmentForm(request.POST or None)
    search_form = forms.AssignmentSearchForm(request.GET or None)
    user_id = request.user.id
    user = request.user.profile
    created_assignment = request.user.assignments.all()
    assignments = Assignment.objects.all()
    assignments_list = Assignment.objects.all().order_by('-created_at')[0:3]
    assignment_count = assignments_list.count()
    created_assignment_count = created_assignment.count()


    if user.role == 'Teacher':
        paginator = Paginator(assignments_list, 10)
        page = request.GET.get('page')
        try:
            assignments_list = paginator.page(page)
        except PageNotAnInteger:
            assignments_list = paginator.page(1)
        except EmptyPage:
            assignments_list = paginator.page(paginator.num_pages)

        if request.method == 'GET':
            if search_form.is_valid():
                q = request.GET['q']
                assignments = assignments.annotate(
                    search=SearchVector('title', 'course_code', 'course_title'),
                    ).filter(search=SearchQuery(q))

                paginator = Paginator(assignments, 10)
                page = request.GET.get('page')
                try:
                    assignments = paginator.page(page)
                except PageNotAnInteger:
                    assignments = paginator.page(1)
                except EmptyPage:
                    assignments = paginator.page(paginator.num_pages)
            else:
                for error in search_form.errors.values():
                    messages(request, error)
                    
                context = {
                    "search_form": search_form,
                    "assignment": assignment_form,
                    "created_assignment_count": created_assignment_count,
                    'created_assignment': created_assignment,
                }
                return render(request, 'home/dashboard.html', context=context)
        context = {
            "created_assignment": created_assignment,
            "assignment": assignment_form,
            "search_form": search_form,

        }
        return render(request, 'home/dashboard.html', context=context)
    else:
        submissions = request.user.submissions.all()
        submissions_list = submissions
        search_form = forms.SubmissionSearchForm(request.GET or None)
        paginator = Paginator(submissions_list, 10)
        page = request.GET.get('page')
        try:
            submissions_list = paginator.page(page)
        except PageNotAnInteger:
            submissions_list = paginator.page(1)
        except EmptyPage:
            submissions_list = paginator.page(paginator.num_pages)

        if request.method == 'GET':
            if search_form.is_valid():
                q = request.GET['q']
                submissions = submissions.annotate(
                    search=SearchVector('matric_number'),
                    ).filter(search=SearchQuery(q))

                paginator = Paginator(submissions, 10)
                page = request.GET.get('page')
                try:
                    submissions = paginator.page(page)
                except PageNotAnInteger:
                    submissions = paginator.page(1)
                except EmptyPage:
                    submissions = paginator.page(paginator.num_pages)

                context = {
                    "search_form": search_form,
                    "submissions": submissions,
                    "assignments_list": assignments_list,
                    }
                return render(request, 'home/studs_home.html', context=context)
        context = {
            "search_form": search_form,
            "submissions": submissions,
            'assignments_list': assignments_list,
            'assignment_count': assignment_count,
        }
        return render(request, 'home/studs_home.html', context=context)


###################################################################################################################################################


@login_required
def assignment_detail(request, id):
    assignment = Assignment.objects.get(id=id)
    initial = {
        "title": assignment.title,
        "upload": assignment.upload,
        "due_date": assignment.due_date,
        "course_code": assignment.course_code,
        "course_title": assignment.course_title
        }
    assignment_form = forms.AssignmentForm(initial=initial)
    context = {
        "single_assignment": assignment,
        "assignment_id": id,
        "assignment": assignment_form
    }
    return render(request, 'home/assignment-detail.html', context=context)

@login_required
def assignment_submissions(request, id):
    assignment_id = id
    if request.user.profile.role != 'Teacher':
        return redirect('home')
    if request.user.profile.role == 'Teacher':
        search_form = forms.SubmissionSearchForm(request.GET or None)
        feedback_form = forms.FeedbackForm(request.POST or None)
        grade_form = forms.GradeForm(request.POST or None)
        assignment = Assignment.objects.get(id=id)
        submissions = assignment.submissions.all()
        submissions_list = submissions
        paginator = Paginator(submissions_list, 10)
        page = request.GET.get('page')
        try:
            submissions_list = paginator.page(page)
        except PageNotAnInteger:
            submissions_list = paginator.page(1)
        except EmptyPage:
            submissions_list = paginator.page(paginator.num_pages)

        if request.method == 'POST':
            if feedback_form.is_valid():
                feedback = request.POST['feedback']
                submission_id = request.POST['submit-feedback']
                submission = Submission.objects.get(id=submission_id)
                submission.feedback = feedback
                submission.save()
            elif grade_form.is_valid():
                grade = request.POST['grade']
                submission_id = request.POST['submit-grade']
                submission = Submission.objects.get(id=submission_id)
                submission.grade = grade
                submission.save()

        if request.method == "GET":
            if search_form.is_valid():
                q = request.GET['q']
                submissions = submissions.annotate(
                    search=SearchVector('matric_number'),
                    ).filter(search=SearchQuery(q))

                paginator = Paginator(submissions, 10)
                page = request.GET.get('page')
                try:
                    submissions = paginator.page(page)
                except PageNotAnInteger:
                    submissions = paginator.page(1)
                except EmptyPage:
                    submissions = paginator.page(paginator.num_pages)

                context = {
                    "search_form": search_form,
                    "submissions": submissions
                }
                return render(request, 'home/assignment-submissions.html', context=context)

        context = {
                "search_form": search_form,
                "submissions": submissions,
                "grade_form": grade_form,
                "feedback_form": feedback_form,
                "assignment_id": assignment_id
            }
        return render(request, 'home/assignment-submissions.html', context=context)

###################################################################################################################################################
@login_required
def delete_assignment(request, id):
    assignment = Assignment.objects.get(id=id)
    user_id = assignment.user_id
    if user_id == request.user.id:
        assignment.delete()
        messages.success(request, "Assignment was successfully deleted")
        return redirect('home')
    else:
        context = {
            "single_assignment": assignment,
            "assignment_id": id
        }
        messages.error(request, "You are not authorized to carry out this operation")
        return render(request, 'home/assignment-detail.html', context=context)


###################################################################################################################################################

@login_required
def edit_assignment(request, id):
    assignment = Assignment.objects.get(id=id)
    user_id = assignment.user_id
    initial = {
        "title": assignment.title,
        "upload": assignment.upload,
        "due_date": assignment.due_date,
        "course_code": assignment.course_code,
        "course_title": assignment.course_title
        }
    assignment_form = forms.AssignmentForm(request.POST, request.FILES, instance=assignment, initial=initial)
    if request.method == "POST":

        if assignment_form.is_valid():
            current_user = request.user.id
            if current_user == user_id:
                assignment_form.save()

templates/home/all_assignment_submmission.html
{% extends 'home/base.html' %}
{% block title %} All Submmissions {% endblock title %}
{% block viewsubmissions %} active {% endblock viewsubmissions  %} 
{% block body %}
          <table class="table table-striped  table-bordered">
          <thead>
            <tr>
                <th>Sn.o</th>
                <th>Title</th>
                <th>Upload</th>
                <th>Date Created</th>
                <th>Due date</th>
                <th>Submissions</th>
            </tr>
          </thead>

          <tbody>
            {% for assignment in assignments %}
              <tr>
                <td>{{ forloop.counter }}</td>
                <td><a href="/assignments/{{ assignment.id }}">{{ assignment.title }}</a></td>
	            <td>
	                <a href="/media/{{ assignment.upload }}" target="_blank">
	                <img width="100" height="100" src="/media/{{ assignment.upload }}" alt="image"></a>
	            </td>
                <td>{{ assignment.created_at }}</td>
                <td>{{ assignment.due_date }}</td>
                <td><a href="/assignments/{{ assignment.id }}/submissions">{{ assignment.submissions.count }}</a></td>
              </tr>
            {% endfor %}
          </tbody>
        </table>

{% endblock  %}

templates/home/all_submmission.html
{% extends 'home/base.html' %}
{% block title %} Submmissions {% endblock title %}
{% block submissions %} active {% endblock submissions %}
{% load static %}
{% block body %}
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th scope="col">S.no.</th>
            <th scope="col">Subject</th>
            <th scope="col">Title</th>
            <th scope="col">Added Date</th>
            <th scope="col">Deadline Date</th>
            <th scope="col">Grade</th>
            <th scope="col">Remarks</th>
            <th scope="col">Feedback</th>
        </tr>
    </thead>
    <tbody>
        {% for  submissions in submission %}
        This is file type {{ submissions.extension_sub}}
        <tr>
            <th scope="row">{{forloop.counter}}</th>
            <td>{{submissions.assignment.user.profile.subject}}</td>
            <td>{{submissions.assignment.title}}</td>
            <td>{{submissions.assignment.created_at}}</td>
            <td>{{submissions.assignment.due_date}}</td>
            <td>{{submissions.grade}}</td>
            <td>{{submissions.feedback}}</td>
            <td class=" ">
                <a href="/assignments/{{submissions.assignment.id}}/detail/" class="btn btn-primary btn-sm view-assignment-detail" style="margin-bottom: 4px;">
                    Detail
                </a>

                <a href="/submissions/{{submissions.id}}/edit" class="btn btn-success btn-sm assignment-submit-btn" style="margin-bottom: 4px;">
                    View/Edit Assignment
                </a>
            </td>
        </tr>	
        {% endfor %}
    </tbody>
</table>
{% endblock %}



<!-- 
{% for submissions in submission %}
 {{submissions.assignment.title}}
{% endfor %} -->

templates/home/assignment-submissions.html
{% extends "home/base.html" %}
{% block title %} Submmission {% endblock %}
{% block body %}
<div>
    {% if submissions %}
    <div class="body">
        <div class="sub-body">
            <div class="row">
            </div>
            <div class="no-assignment">
                <table class="table-striped table-bordered table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Student Name</th>
                            <th>Upload</th>
                            <th>Date submitted</th>
                            <th>Grade</th>
                            <th>Feedback</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for submission in submissions %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ submission.user.first_name }}</td>
                            {% if submission.upload == '' %}
                            <td>None</td>
                            {% else %}
                            <td>{{ submission.upload }}</td>
                            {% endif %}
                            <td>{{ submission.submitted_at }}</td>
                            <td>
                                <form method="POST" enctype="multipart/form-data" class="feedback-form">
                                    {% csrf_token %}
                                    {% if submission.grade != "No grade yet" %}
                                    <input class="form-control"  type="number" value="{{submission.grade}}" name="grade" id="id_grade">
                                    {% else %}
                                    <input class="form-control"  type="number" name="grade" required id="id_grade">
                                    {% endif %}
                                    <button type="submit" class="btn btn-primary mt-1" name="submit-grade" value="{{ submission.id }}">
                                        <a>Send</a>
                                    </button>
                                </form>
                            </td>
                            <td>

                                <form method="POST" enctype="multipart/form-data" class="feedback-form">
                                    {% csrf_token %}
                                  {% if submission.feedback != 'No feedback yet' %}
                                    <input class="form-control"  type="text" value="{{ submission.feedback }}" name="feedback" required id="id_feedback">
                                  {% else %}
                                    <input class="form-control"  type="text" name="feedback" required id="id_feedback">
                                    {% endif %}
                                    <button class="btn btn-primary mt-1" type="submit" name="submit-feedback" value="{{ submission.id }}">
                                        <a href="">Send</a>
                                    </button>
                                </form>
                            </td>
                      
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!--     {% for submission in submissions %}
      <div id="modal-{{ submission.id }}" class="modal">
        <div class="modal-content">
          <h4>Grade Submission</h4>
          <form method="POST" enctype="multipart/form-data" class="feedback-form">
            {% csrf_token %}
            {{ grade_form.grade }}
            <button type="submit" name="submit-grade" value="{{ submission.id }}">
            </button>
          </form>
        </div>
      </div>
    {% endfor %} -->
    {% else %}
    <div class="body">
        <div class="sub-body">
            <div class="no-assignment">
                <p> No submissions yet </p>
            </div>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

templates/home/assignment_detail.html
{% extends "home/base.html" %}
{% block title %} Assignment Detail{% endblock %}
{% load static %}
{% block body %}
<table class="table">
    <tbody>
        <tr>
            <th> Subject </th>
            <td> {{assignment.user.profile.subject}} </td>
        </tr>
        <tr>
            <th> Deadline </th>
            <td> {{ assignment.due_date }} </td>
        </tr>
        <tr>
            <th> Title </th>
            <td> {{ assignment.title }} </td>
        </tr>
        <tr>
            <th> Description </th>
            <td>
                <div style="min-height: 70px;">
                    {{assignment.descprition}} </div>
            </td>
        </tr>
        <tr>
            <th> Year </th>
            <td> {% now "Y" %} </td>
        </tr>
        <tr>
            <th> Files </th>

            <td>
                {% if assignment.upload %}
                {% if '.pdf' in assignment.extension_ass %}
                <a data-caption="" title="Click to preview" target="_blank" class="row pdf" href="/media/{{assignment.upload}}">
                    <div class="col-sm-5">
                        <span id="https://veda-app" class="">
                            <img class="media-object" style="height: 80px; width:70px;max-width: 100%;" src="{% static 'img/pdf.png'  %}" alt="">
                            <!-- <img class="media-object" src="..." alt="..."> -->
                        </span>
                    </div>
                    <div class="col-sm-7">
                        <h4 class="media-heading" style="color: #000;"> </h4>
                    </div>
                    <div class="col-sm-12">
                        <hr>
                    </div>
                </a>
                {% else %}
                <a data-caption="" title="Click to preview" target="_blank" class="row " href="/media/{{assignment.upload}}">
                    <img class="media-object" style="height: 150px; width:auto; max-width: 100%;" src="/media/{{assignment.upload}}" alt="">
                    {% endif %}
                {% endif %}
            </td>
        </tr>
    </tbody>
</table>
{% endblock %}

templates/home/changePassword.html
{% extends 'home/base.html'  %}
{% block Password %} active {% endblock Password %}
{% block title %} Update Password {% endblock title %}
{% block body %}
  <div class="col-md-10 mt-2">
        <h3>Change your Password</h3>
    {% load crispy_forms_tags %}
      <form method="Post">
        {% csrf_token %}
        {{form|crispy}}
        <button class="btn btn-primary">Submit</button>
    </form>
  </div>

{% endblock %}

templates/home/create_assignment.html
{% extends "home/base.html" %}
{% block title %}Assignment Management System{% endblock %}
{% block Assignments %} active {% endblock Assignments  %} 
{% block  body %}

<form id="assignment-submit-form" enctype="multipart/form-data" method="POST"  aaction="{% url 'add_assignment'%}">
  {% csrf_token %}
    <div class="form-group">
        <label>Title</label>
        <input name="title" id="title" class="form-control">
    </div>
    <div class="form-group">
        <label>Deadline</label>
        <input type="date" name="due_date" id="due_date" class="form-control">
    </div>
    <div class="form-group">
        <label>Description</label>
        <textarea name="description" id="description" rows="5" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label>Image/File (jpg,png,pdf)</label>
        <input multiple="" type="file" class="form-control" id="edit-choose-files" name="upload" data-resize="1080" accept=".jpg,.png,.jpeg,.pdf" >
    </div>

    
    <table id="edit-preview-table" class="table">
        <thead id="edit-columns"><tr><td style="width: 100%;"></td></tr></thead>
        <tbody id="edit-previews">

        </tbody>
    </table>

    <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>
<script type="text/javascript">
    (function(global) {
        var imagesPerRow = 1,
            chooseFiles,
            columns,
            previews;

        function PreviewImages() {
            $('#edit-preview-table #edit-previews').html("");
            $('#edit-preview-table').fadeIn();
            var row;
            Array.prototype.forEach.call(chooseFiles.files, function(file, index) {
                var cindex = index % imagesPerRow,
                    oFReader = new FileReader(),
                    cell,
                    image;

                if (cindex === 0) {
                    row = previews.insertRow(Math.ceil(index / imagesPerRow));
                }

                image = document.createElement("img");
                image.id = "img_" + index;
                image.style.width = "200px";
                image.style.height = "auto";
                cell = row.insertCell(cindex);
                cell.appendChild(image);



                cell = row.insertCell(1);



                oFReader.addEventListener("load", function assignImageSrc(evt) {
                    image.src = evt.target.result;
                    this.removeEventListener("load", assignImageSrc);
                }, false);

                oFReader.readAsDataURL(file);
            });
        }


        // global.removeEventListener("load", windowLoadHandler);
        chooseFiles = document.getElementById("edit-choose-files");
        columns = document.getElementById("edit-columns");
        previews = document.getElementById("edit-previews");

        var row = columns.insertRow(-1),
            header,
            i;

        for (i = 0; i < imagesPerRow; i += 1) {
            header = row.insertCell(-1);
            header.style.width = (100 / imagesPerRow) + "%";
        }
        chooseFiles.addEventListener("change", PreviewImages, false);
    }(window));







    function getAssignmentsPage() {
        var fromDate = $('#from-date').val();
        var toDate = $('#to-date').val();
        var filter = $('#filter').val();

        if (fromDate != "" && toDate != "" && filter != "") {
            reloadTable();
        }
    }

    function getNotesPage() {
        var fromDate = $('#from-date').val();
        var toDate = $('#to-date').val();

        if (fromDate != "" && toDate != "") {
            reloadNotesTable();
        }
    }
</script>
{% endblock %}

templates/home/submission-detail.html
{% extends "home/base.html" %}
{% block title %}Assignment Management System {% endblock title%}
{% load static %}
{% block body %}
<!-- <div class="container assignment-detail">
  <div class="row single-assignment">
    <div class="col s12">
       <h4> Submission Details </h4>
    </div>
    <div class="col s12">
      <p> Upload: {{ single_submission.upload }} </p> </div>
    <div class="col s12">
      <p> Submission Date: {{ single_submission.submitted_at }} </p> 
    </div>
    <div class="col s12">
      <p> Submmitted Assigment: {{ single_submission.assignment.title }} </p> 
    </div>
  </div> -->
<table class="table ">
    <tbody>
        <h4 class="mt-2 ml-2">Submmission Detail</h4>
        <tr>
            <th> Subject </th>
            <td> {{single_submission.assignment.user.profile.subject}} </td>
        </tr>
        <tr>
            <th> Deadline </th>
            <td>{{ single_submission.assignment.due_date }}</td>
        </tr>
        <tr>
            <th> Title </th>
            <td> {{ single_submission.assignment.title }} </td>
        </tr>
        <tr>
            <th> Submmitted At </th>
            <td>{{ single_submission.submitted_at }} </td>
        </tr>
    </tbody>
</table>
<hr>
<form id="assignment-submit-form" enctype="multipart/form-data" method="POST" aaction="{% url 'submission_detail' id=submission_id %}">
    {% csrf_token %}
    <h4>Edit Submmission</h4>
    <div class="form-group">
        <label>Description</label>
        <textarea name="descprition" required id="id_descprition" rows="5" class="form-control">{{single_submission.descprition}}</textarea>
    </div>
    <div class="form-group">

        <label>Image/File (jpg,png,pdf) Currently : 
          {% if '.pdf' == single_submission.extension_sub %} 
          <a href="/media/{{single_submission.upload}}" target="_blank">
            <img class="media-object" style="height: 80px; width:70px;max-width: 100%;" src="{% static 'img/pdf.png'  %}" alt="">
          </a>
          {% elif single_submission.upload %}
          <a href="/media/{{single_submission.upload}}" target="_blank"> <img class="media-object" style="height: 80px; width:70px;max-width: 100%;" src="/media/{{single_submission.upload}}" > </a> 
          {% else %}
            No files
          {% endif  %}
        </label>
        <!-- {{ submission.upload }} -->
        <input type="file" class="form-control" id="edit-choose-files" name="upload" data-resize="1080" accept=".jpg,.png,.jpeg,.pdf">
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
    <table id="edit-preview-table" class="table">
        <thead id="edit-columns">
            <tr>
                <td style="width: 100%;"></td>
            </tr>
        </thead>
        <tbody id="edit-previews">
        </tbody>
    </table>
</form>
<!-- 
    <div class="modal-content">
      <h4>Edit Submission</h4>
      <div class="edit-modal">
        <div class="modal-container">
          <form method="POST" action="{% url 'submission_detail' id=submission_id %}" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
              <div class="file-field input-field col s12">
                <div class="btn col s6">
                  <span>File</span>
                  {{ submission.upload }}
                </div>
                <input type="text" name="descprition" value="{{single_submission.descprition}}" required id="id_descprition">
              </div>
            </div>
            <button class="btn waves-effect waves-light modal-action modal-close" type="submit" name="edit-submission">Edit submission
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div>
  </div> -->
<form method="POST" action={% url 'delete_submission' id=submission_id %}>
    {% csrf_token %}
    <div class="edit-delete">
        <button class="btn btn-danger" type="submit" name="delete-submission">Delete Submmission
        </button>
    </div>
</form>
{% endblock %}